<?php
$RSIDEBAR_DATA = <<<END_RSIDEBAR_DATA
<h4>Upcoming Events <a href="/submit-event.php">[add]</a></h4>
<h4 class="eventmonth">February</h4>
<h4>User Group Events</h4>
<span class="event_USA vevent"><abbr title="2024-02-11" class="dtstart">11</abbr>. <a href="/cal.php?id=3760" class="summary">Los Angeles PHP Developers Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-12" class="dtstart">12</abbr>. <a href="/cal.php?id=4308" class="summary">Queen City (Charlotte) PHP</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-02-13" class="dtstart">13</abbr>. <a href="/cal.php?id=1385" class="summary">Hamburg</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-13" class="dtstart">13</abbr>. <a href="/cal.php?id=1523" class="summary">Dallas PHP/MySQL Users Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-13" class="dtstart">13</abbr>. <a href="/cal.php?id=1665" class="summary">OKC PHP Meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-13" class="dtstart">13</abbr>. <a href="/cal.php?id=1670" class="summary">Dallas PHP Users Group (DPUG)</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-13" class="dtstart">13</abbr>. <a href="/cal.php?id=1847" class="summary">Nashville PHP User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-13" class="dtstart">13</abbr>. <a href="/cal.php?id=3643" class="summary">Oklahoma City PHP User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-13" class="dtstart">13</abbr>. <a href="/cal.php?id=3980" class="summary">Buffalo PHP Meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-13" class="dtstart">13</abbr>. <a href="/cal.php?id=5701" class="summary">Milwaukee PHP User\&#039;s Group</a></span><br />
<span class="event_NLD vevent"><abbr title="2024-02-13" class="dtstart">13</abbr>. <a href="/cal.php?id=6148" class="summary">PHP Amersfoort</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-02-14" class="dtstart">14</abbr>. <a href="/cal.php?id=3684" class="summary">PHP User Group Stuttgart</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-14" class="dtstart">14</abbr>. <a href="/cal.php?id=4222" class="summary">South Florida PHP Users Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-14" class="dtstart">14</abbr>. <a href="/cal.php?id=5212" class="summary">DC PHP Developer&#039;s Community</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-14" class="dtstart">14</abbr>. <a href="/cal.php?id=5388" class="summary">VenturaPHP Developers Meetup</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-02-14" class="dtstart">14</abbr>. <a href="/cal.php?id=5910" class="summary">PHP Hampshire meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-14" class="dtstart">14</abbr>. <a href="/cal.php?id=6940" class="summary">Peak PHP</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-15" class="dtstart">15</abbr>. <a href="/cal.php?id=1719" class="summary">OINK-PUG (Cincinnati, Ohio)</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-15" class="dtstart">15</abbr>. <a href="/cal.php?id=1820" class="summary">Utah PHP Users Group Meeting</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-15" class="dtstart">15</abbr>. <a href="/cal.php?id=4507" class="summary">Denver - FRPUG</a></span><br />
<span class="event_NLD vevent"><abbr title="2024-02-15" class="dtstart">15</abbr>. <a href="/cal.php?id=5343" class="summary">AmsterdamPHP Meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-15" class="dtstart">15</abbr>. <a href="/cal.php?id=5372" class="summary">San Diego PHP</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-15" class="dtstart">15</abbr>. <a href="/cal.php?id=5427" class="summary">UPHPU Utah PHP Users</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-02-15" class="dtstart">15</abbr>. <a href="/cal.php?id=5723" class="summary">Kent PHP User Group</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-02-15" class="dtstart">15</abbr>. <a href="/cal.php?id=6538" class="summary">PHP North East</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-17" class="dtstart">17</abbr>. <a href="/cal.php?id=2449" class="summary">Los Angeles LAMPsig</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-17" class="dtstart">17</abbr>. <a href="/cal.php?id=5401" class="summary">Kansas City</a></span><br />
<span class="event_TUR vevent"><abbr title="2024-02-17" class="dtstart">17</abbr>. <a href="/cal.php?id=6176" class="summary">PHPKonf: PHP User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-17" class="dtstart">17</abbr>. <a href="/cal.php?id=6456" class="summary">UpstatePHP</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-18" class="dtstart">18</abbr>. <a href="/cal.php?id=6118" class="summary">PHP User Group Hack Night</a></span><br />
<span class="event_LTU vevent"><abbr title="2024-02-18" class="dtstart">18</abbr>. <a href="/cal.php?id=6400" class="summary">Kaunas PHP community meetup</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-02-19" class="dtstart">19</abbr>. <a href="/cal.php?id=5533" class="summary">BrightonPHP User Group</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-02-19" class="dtstart">19</abbr>. <a href="/cal.php?id=6396" class="summary">PHPMinds User Group</a></span><br />
<span class="event_AUS vevent"><abbr title="2024-02-20" class="dtstart">20</abbr>. <a href="/cal.php?id=2246" class="summary">PHP Brisbane Meetup Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-20" class="dtstart">20</abbr>. <a href="/cal.php?id=3761" class="summary">Chattanooga PHP Developers</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-02-20" class="dtstart">20</abbr>. <a href="/cal.php?id=4725" class="summary">PHP North-East User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-20" class="dtstart">20</abbr>. <a href="/cal.php?id=5222" class="summary">NWO-PUG User Group Meeting</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-20" class="dtstart">20</abbr>. <a href="/cal.php?id=5370" class="summary">Lake / Kenosha PHP User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-20" class="dtstart">20</abbr>. <a href="/cal.php?id=5474" class="summary">Tallahassee PHP User Group</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-02-20" class="dtstart">20</abbr>. <a href="/cal.php?id=5797" class="summary">Edinburgh PHP User Group</a></span><br />
<span class="event_AUS vevent"><abbr title="2024-02-20" class="dtstart">20</abbr>. <a href="/cal.php?id=5831" class="summary">Melbourne PHP Users Group</a></span><br />
<span class="event_HRV vevent"><abbr title="2024-02-20" class="dtstart">20</abbr>. <a href="/cal.php?id=5953" class="summary">Zagreb PHP Meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-20" class="dtstart">20</abbr>. <a href="/cal.php?id=5963" class="summary">Oklahoma PHP User Group</a></span><br />
<span class="event_NLD vevent"><abbr title="2024-02-20" class="dtstart">20</abbr>. <a href="/cal.php?id=6226" class="summary">PHP.FRL Monthly Meeting</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-22" class="dtstart">22</abbr>. <a href="/cal.php?id=4256" class="summary">Memphis PHP</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-02-22" class="dtstart">22</abbr>. <a href="/cal.php?id=6245" class="summary">PHP UserGroup Erlangen-Nürnberg</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-26" class="dtstart">26</abbr>. <a href="/cal.php?id=4648" class="summary">Tampa Bay Florida PHP</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-02-26" class="dtstart">26</abbr>. <a href="/cal.php?id=5985" class="summary">PHP Cambridge</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-27" class="dtstart">27</abbr>. <a href="/cal.php?id=384" class="summary">AzPHP</a></span><br />
<span class="event_USA vevent"><abbr title="2024-02-27" class="dtstart">27</abbr>. <a href="/cal.php?id=409" class="summary">New York</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-02-27" class="dtstart">27</abbr>. <a href="/cal.php?id=2660" class="summary">PHPUG Wuerzburg</a></span><br />
<span class="event_AUS vevent"><abbr title="2024-02-27" class="dtstart">27</abbr>. <a href="/cal.php?id=3653" class="summary">Brisbane PHP User Group</a></span><br />
<span class="event_ITA vevent"><abbr title="2024-02-27" class="dtstart">27</abbr>. <a href="/cal.php?id=4626" class="summary">PHP User Group Roma</a></span><br />
<span class="event_BRA vevent"><abbr title="2024-02-27" class="dtstart">27</abbr>. <a href="/cal.php?id=5276" class="summary">PHPUBSP</a></span><br />
<h4 class="eventmonth">March</h4>
<h4>User Group Events</h4>
<span class="event_NLD vevent"><abbr title="2024-03-01" class="dtstart">01</abbr>. <a href="/cal.php?id=6106" class="summary">SweetlakePHP</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-02" class="dtstart">02</abbr>. <a href="/cal.php?id=5955" class="summary">PHP Dorset</a></span><br />
<span class="event_CHN vevent"><abbr title="2024-03-03" class="dtstart">03</abbr>. <a href="/cal.php?id=1923" class="summary">PHP meeting online in China</a></span><br />
<span class="event_BOL vevent"><abbr title="2024-03-03" class="dtstart">03</abbr>. <a href="/cal.php?id=2540" class="summary">meeting de LAMPistas en La Paz</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-03" class="dtstart">03</abbr>. <a href="/cal.php?id=6117" class="summary">PHP User Group Meeting</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-05" class="dtstart">05</abbr>. <a href="/cal.php?id=1745" class="summary">SW Florida Linux Users Group</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-03-05" class="dtstart">05</abbr>. <a href="/cal.php?id=2814" class="summary">Berlin PHP Usergroup Meeting</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-05" class="dtstart">05</abbr>. <a href="/cal.php?id=3294" class="summary">PHPNW: PHP North West user group</a></span><br />
<span class="event_CAN vevent"><abbr title="2024-03-05" class="dtstart">05</abbr>. <a href="/cal.php?id=5527" class="summary">Greater Toronto Area PHP UG</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-05" class="dtstart">05</abbr>. <a href="/cal.php?id=5952" class="summary">PHP London</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-05" class="dtstart">05</abbr>. <a href="/cal.php?id=5971" class="summary">PHPem: PHP East Midlands</a></span><br />
<span class="event_NLD vevent"><abbr title="2024-03-05" class="dtstart">05</abbr>. <a href="/cal.php?id=6090" class="summary">GroningenPHP</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-06" class="dtstart">06</abbr>. <a href="/cal.php?id=2682" class="summary">BostonPHP</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-06" class="dtstart">06</abbr>. <a href="/cal.php?id=3793" class="summary">Pittsburgh PHP Meetup Group</a></span><br />
<span class="event_MYS vevent"><abbr title="2024-03-06" class="dtstart">06</abbr>. <a href="/cal.php?id=5473" class="summary">Kuala Lumpur PHP</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-06" class="dtstart">06</abbr>. <a href="/cal.php?id=6873" class="summary">Aberdeen PHP User Group</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-03-07" class="dtstart">07</abbr>. <a href="/cal.php?id=272" class="summary">Hannover</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-07" class="dtstart">07</abbr>. <a href="/cal.php?id=561" class="summary">Meetup Day</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-07" class="dtstart">07</abbr>. <a href="/cal.php?id=1632" class="summary">Boston PHP Meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-07" class="dtstart">07</abbr>. <a href="/cal.php?id=1706" class="summary">Atlanta PHP User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-07" class="dtstart">07</abbr>. <a href="/cal.php?id=2418" class="summary">Seattle PHP Meetup Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-07" class="dtstart">07</abbr>. <a href="/cal.php?id=2932" class="summary">SF PHP Meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-07" class="dtstart">07</abbr>. <a href="/cal.php?id=3861" class="summary">Minnesota PHP User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-07" class="dtstart">07</abbr>. <a href="/cal.php?id=4014" class="summary">OrlandoPHP User Group</a></span><br />
<span class="event_NLD vevent"><abbr title="2024-03-07" class="dtstart">07</abbr>. <a href="/cal.php?id=5519" class="summary">PHPTwente Meetup</a></span><br />
<span class="event_LTU vevent"><abbr title="2024-03-07" class="dtstart">07</abbr>. <a href="/cal.php?id=5685" class="summary">Vilnius PHP community meetup</a></span><br />
<span class="event_MEX vevent"><abbr title="2024-03-09" class="dtstart">09</abbr>. <a href="/cal.php?id=4258" class="summary">Nezahualcoyotl PHP Ramptors</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-10" class="dtstart">10</abbr>. <a href="/cal.php?id=3760" class="summary">Los Angeles PHP Developers Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-11" class="dtstart">11</abbr>. <a href="/cal.php?id=4308" class="summary">Queen City (Charlotte) PHP</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-03-12" class="dtstart">12</abbr>. <a href="/cal.php?id=1385" class="summary">Hamburg</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-12" class="dtstart">12</abbr>. <a href="/cal.php?id=1523" class="summary">Dallas PHP/MySQL Users Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-12" class="dtstart">12</abbr>. <a href="/cal.php?id=1665" class="summary">OKC PHP Meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-12" class="dtstart">12</abbr>. <a href="/cal.php?id=1670" class="summary">Dallas PHP Users Group (DPUG)</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-12" class="dtstart">12</abbr>. <a href="/cal.php?id=1847" class="summary">Nashville PHP User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-12" class="dtstart">12</abbr>. <a href="/cal.php?id=3643" class="summary">Oklahoma City PHP User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-12" class="dtstart">12</abbr>. <a href="/cal.php?id=3980" class="summary">Buffalo PHP Meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-12" class="dtstart">12</abbr>. <a href="/cal.php?id=5701" class="summary">Milwaukee PHP User\&#039;s Group</a></span><br />
<span class="event_NLD vevent"><abbr title="2024-03-12" class="dtstart">12</abbr>. <a href="/cal.php?id=6148" class="summary">PHP Amersfoort</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-03-13" class="dtstart">13</abbr>. <a href="/cal.php?id=3684" class="summary">PHP User Group Stuttgart</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-13" class="dtstart">13</abbr>. <a href="/cal.php?id=4222" class="summary">South Florida PHP Users Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-13" class="dtstart">13</abbr>. <a href="/cal.php?id=5212" class="summary">DC PHP Developer&#039;s Community</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-13" class="dtstart">13</abbr>. <a href="/cal.php?id=5388" class="summary">VenturaPHP Developers Meetup</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-13" class="dtstart">13</abbr>. <a href="/cal.php?id=5910" class="summary">PHP Hampshire meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-13" class="dtstart">13</abbr>. <a href="/cal.php?id=6940" class="summary">Peak PHP</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-14" class="dtstart">14</abbr>. <a href="/cal.php?id=1652" class="summary">Austin PHP Meetup</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-03-14" class="dtstart">14</abbr>. <a href="/cal.php?id=1848" class="summary">Meeting usergroup Dortmund</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-03-14" class="dtstart">14</abbr>. <a href="/cal.php?id=1946" class="summary">PHP Usergroup Frankfurt/Main</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-14" class="dtstart">14</abbr>. <a href="/cal.php?id=5322" class="summary">Seattle PHP Meetup/Users Group</a></span><br />
<span class="event_NLD vevent"><abbr title="2024-03-14" class="dtstart">14</abbr>. <a href="/cal.php?id=5839" class="summary">010PHP Rotterdam User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-16" class="dtstart">16</abbr>. <a href="/cal.php?id=2449" class="summary">Los Angeles LAMPsig</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-16" class="dtstart">16</abbr>. <a href="/cal.php?id=5401" class="summary">Kansas City</a></span><br />
<span class="event_TUR vevent"><abbr title="2024-03-16" class="dtstart">16</abbr>. <a href="/cal.php?id=6176" class="summary">PHPKonf: PHP User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-16" class="dtstart">16</abbr>. <a href="/cal.php?id=6456" class="summary">UpstatePHP</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-17" class="dtstart">17</abbr>. <a href="/cal.php?id=6118" class="summary">PHP User Group Hack Night</a></span><br />
<span class="event_LTU vevent"><abbr title="2024-03-17" class="dtstart">17</abbr>. <a href="/cal.php?id=6400" class="summary">Kaunas PHP community meetup</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-18" class="dtstart">18</abbr>. <a href="/cal.php?id=5533" class="summary">BrightonPHP User Group</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-18" class="dtstart">18</abbr>. <a href="/cal.php?id=6396" class="summary">PHPMinds User Group</a></span><br />
<span class="event_AUS vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=2246" class="summary">PHP Brisbane Meetup Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=3761" class="summary">Chattanooga PHP Developers</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=4725" class="summary">PHP North-East User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=5222" class="summary">NWO-PUG User Group Meeting</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=5370" class="summary">Lake / Kenosha PHP User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=5474" class="summary">Tallahassee PHP User Group</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=5797" class="summary">Edinburgh PHP User Group</a></span><br />
<span class="event_AUS vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=5831" class="summary">Melbourne PHP Users Group</a></span><br />
<span class="event_HRV vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=5953" class="summary">Zagreb PHP Meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=5963" class="summary">Oklahoma PHP User Group</a></span><br />
<span class="event_NLD vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=6226" class="summary">PHP.FRL Monthly Meeting</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-19" class="dtstart">19</abbr>. <a href="/cal.php?id=7154" class="summary">PHP North East</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-21" class="dtstart">21</abbr>. <a href="/cal.php?id=1719" class="summary">OINK-PUG (Cincinnati, Ohio)</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-21" class="dtstart">21</abbr>. <a href="/cal.php?id=1820" class="summary">Utah PHP Users Group Meeting</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-21" class="dtstart">21</abbr>. <a href="/cal.php?id=4507" class="summary">Denver - FRPUG</a></span><br />
<span class="event_NLD vevent"><abbr title="2024-03-21" class="dtstart">21</abbr>. <a href="/cal.php?id=5343" class="summary">AmsterdamPHP Meetup</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-21" class="dtstart">21</abbr>. <a href="/cal.php?id=5372" class="summary">San Diego PHP</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-21" class="dtstart">21</abbr>. <a href="/cal.php?id=5427" class="summary">UPHPU Utah PHP Users</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-21" class="dtstart">21</abbr>. <a href="/cal.php?id=5723" class="summary">Kent PHP User Group</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-25" class="dtstart">25</abbr>. <a href="/cal.php?id=4648" class="summary">Tampa Bay Florida PHP</a></span><br />
<span class="event_GBR vevent"><abbr title="2024-03-25" class="dtstart">25</abbr>. <a href="/cal.php?id=5985" class="summary">PHP Cambridge</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-26" class="dtstart">26</abbr>. <a href="/cal.php?id=384" class="summary">AzPHP</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-26" class="dtstart">26</abbr>. <a href="/cal.php?id=409" class="summary">New York</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-03-26" class="dtstart">26</abbr>. <a href="/cal.php?id=2660" class="summary">PHPUG Wuerzburg</a></span><br />
<span class="event_AUS vevent"><abbr title="2024-03-26" class="dtstart">26</abbr>. <a href="/cal.php?id=3653" class="summary">Brisbane PHP User Group</a></span><br />
<span class="event_ITA vevent"><abbr title="2024-03-26" class="dtstart">26</abbr>. <a href="/cal.php?id=4626" class="summary">PHP User Group Roma</a></span><br />
<span class="event_BRA vevent"><abbr title="2024-03-26" class="dtstart">26</abbr>. <a href="/cal.php?id=5276" class="summary">PHPUBSP</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-28" class="dtstart">28</abbr>. <a href="/cal.php?id=4256" class="summary">Memphis PHP</a></span><br />
<span class="event_DEU vevent"><abbr title="2024-03-28" class="dtstart">28</abbr>. <a href="/cal.php?id=6245" class="summary">PHP UserGroup Erlangen-Nürnberg</a></span><br />
<h4>Training</h4>
<span class="event_IND vevent"><abbr title="2024-03-02" class="dtstart">02</abbr>. <a href="/cal.php?id=3560" class="summary">Core and Advanced PHP Workshop</a></span><br />
<span class="event_FRA vevent"><abbr title="2024-03-04" class="dtstart">04</abbr>. <a href="/cal.php?id=5782" class="summary">Formation PHP 7</a></span><br />
<span class="event_FRA vevent"><abbr title="2024-03-04" class="dtstart">04</abbr>. <a href="/cal.php?id=5798" class="summary">Formation Angular &amp; PHP - France</a></span><br />
<span class="event_USA vevent"><abbr title="2024-03-05" class="dtstart">05</abbr>. <a href="/cal.php?id=1490" class="summary">PHP Class at CalTek</a></span><br />
<span class="event_FRA vevent"><abbr title="2024-03-11" class="dtstart">11</abbr>. <a href="/cal.php?id=5700" class="summary">Formation PHP MySQL - France</a></span><br />
<span class="event_FRA vevent"><abbr title="2024-03-17" class="dtstart">17</abbr>. <a href="/cal.php?id=5978" class="summary">Formation Zend Framework</a></span><br />
<span class="event_FRA vevent"><abbr title="2024-03-18" class="dtstart">18</abbr>. <a href="/cal.php?id=5992" class="summary">Formation JavaScript PHP</a></span><br />
<span class="event_FRA vevent"><abbr title="2024-03-25" class="dtstart">25</abbr>. <a href="/cal.php?id=5384" class="summary">Formation Laravel France</a></span><br />
<span class="event_FRA vevent"><abbr title="2024-03-25" class="dtstart">25</abbr>. <a href="/cal.php?id=5699" class="summary">Formation PHP avancé - France</a></span><br />
END_RSIDEBAR_DATA;
