<?php
$CONF_TEASER = array (
  'conference' => 
  array (
    'https://www.php.net/conferences/index.php#2024-01-24-1' => 'PHP UK Conference 2024',
    'https://www.php.net/conferences/index.php#2024-01-20-1' => 'PHP Conference Odawara 2024',
    'https://www.php.net/conferences/index.php#id2024-01-15-3' => 'SymfonyCon Vienna 2024',
    'https://www.php.net/conferences/index.php#id2024-01-15-2' => 'SymfonyLive Paris 2024',
    'https://www.php.net/conferences/index.php#2024-01-13-1' => 'Web Summer Camp 2024',
    'https://www.php.net/conferences/index.php#2024-01-12-1' => 'Laravel Live Denmark 2024',
    'https://www.php.net/conferences/index.php#2024-01-07-1' => 'PHP Conference Fukuoka 2024',
    'https://www.php.net/conferences/index.php#2024-01-06-1' => 'PHP Conference Kagawa 2024',
    'https://www.php.net/conferences/index.php#2024-01-05-1' => 'Drupal Mountain Camp 2024',
    'https://www.php.net/conferences/index.php#2023-11-22-1' => 'International PHP Conference Berlin 2024',
  ),
)
?>